[package]
name = "core_name_conflict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor = { git = "https://github.com/LechintanTudor/anchor", commit = "d62cb1c" }
